### ISSUE TITLE
Update nanopb version to resolve issue with CMake >= 3.17

### ISSUE THREAD

**Issue by kent-mcleod** [seL4/sel4test-manifest#10]
The version of nanopb that sel4test-manifest downloads should be updated to include the upstream fix linked below. 
Context: https://github.com/nanopb/nanopb/commit/f2f1e13e8d7d502dcae6a5ad3552ead5b35fe6bc

This will address the CMake warning that gets printed when building sel4test with a cmake version >= 3.17.

```
CMake Warning (dev) at /usr/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:426 (message):
  The package name passed to `find_package_handle_standard_args` (NANOPB)
  does not match the name of the calling package (Nanopb).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
```

**Comment by axel-h** [comment]
Shouldn't we take the next official release then, which is 0.4.3 at https://github.com/nanopb/nanopb/commit/1466e6f953835b191a7f5acf0c06c941d4cd33d9
