### ISSUE TITLE
Some errors running ia32 test.

### ISSUE THREAD

**Issue by GooTal** [seL4/sel4test-manifest#18]
I followed this guide: https://docs.sel4.systems/projects/sel4test/ , trying to run the ia32 test. Here are my steps.
```
mkdir sel4test
cd sel4test
repo init -u https://github.com/seL4/sel4test-manifest.git 
repo sync
mkdir ia32_build
cd ia32_build
../init-build.sh -DPLATFORM=ia32 -DRELEASE=TRUE -DSIMULATION=TRUE
ninja
./simulate
```
The test started but some errors occurred, can anyone tell me what`s wrong with it? Much thanks.

![image](https://user-images.githubusercontent.com/40800103/156483485-90c0f199-086b-4474-840e-bd54c2a10309.png)
 
At last, some tests diabled, 
![image](https://user-images.githubusercontent.com/40800103/156483693-4287cb76-77bd-46d2-a0e0-e5b16fdbf0a5.png)

Thanks if you could help.

**Comment by lsf37** [comment]
The test succeeded, you are seeing the expected output.

**Comment by GooTal** [comment]
oh, thank you so much! 
I am a beginner trying to port sel4 to Loongson architecture, it`s quite challenging. I`m learning from the supported hardware listed on this website: https://docs.sel4.systems/Hardware/ and trying to figure out how to port the sel4 kernel.  I`d be much appreciated if you could recommend some material that might be helpful to port the sel4 kernel.
Thanks a lot.

**Comment by lsf37** [comment]
No worries. Please open only one issue per problem, we see them coming in on all repositories, and having multiple ones that are the same problem but have issues on different repos creates unnecessary work.

For porting seL4 to a new platform, have you seen this page? <https://docs.sel4.systems/projects/sel4/porting.html>

**Comment by axel-h** [comment]
> I am a beginner trying to port sel4 to Loongson architecture

That sounds interesting, looking forward to see seL4test running on a QEMU there.
