### ISSUE TITLE
Missing Version 8 Compatible Manifest

### ISSUE THREAD

**Issue by iai-jsaina** [seL4/sel4test-manifest#4]
Version 9 breaks the build for the zynqmp architecture, so default.xml doesn't work, and there is no manifest for version 8. I tried making a manifest to use the version 8 compatible tags, which also failed.

If someone could add a version 8 sel4 test manifest (that builds for zynqmp), it would be appreciated.

**Comment by kent-mcleod** [comment]
Between version 7.0.0 and 8.0.0 we started tagging default.xml with the release version. 
 the version 8.0.0 sel4test-manifest is the default.xml here: https://github.com/seL4/sel4test-manifest/tree/8.0.0

**Comment by seL4-IAI** [comment]
For others wondering how to get repo to use a manifest from a specific tag, use the option:

-b refs/tags/(tag name)

e.g:

repo init -u https://github.com/seL4/sel4test-manifest -b refs/tags/8.0.0
