### ISSUE TITLE
MCS Manifest Does Not Work

### ISSUE THREAD

**Issue by Jesse-Millwood** [seL4/sel4test-manifest#5]
There is no `new-rt` branch of seL4. Is it intended to be `10.0.0-mcs`?

**Comment by pingerino** [comment]
Hi @Jesse-Millwood, the `new-rt` branch is constantly rebased during development so we don't release it externally. I'll try to get a working mcs manifest for the next release. 

What specifically do you need? I'm happy to push some code out.

**Comment by Jesse-Millwood** [comment]
@pingerino thanks for the response. Is the `new-rt` branch a Data61 internal branch? 
I just wanted to build the mcs kernel and get a better feel for the API changes. I got it building with the `default.xml` manifest and the `mcs-tutorials` kernel branch though. So I think I'm good for now, thanks!

**Comment by pingerino** [comment]
Yes, `new-rt` is internal as we rewrite history all the time on it as verification progresses. I'll try to get a working sel4test manifest for our upcoming release out, but it could take a while given our workload currently.

**Comment by lsf37** [comment]
Closing this, since MCS is now part of the master branch.
