### ISSUE TITLE
ltimer_default_init() undefined for target platform spike and ariane

### ISSUE THREAD

**Issue by niwis** [seL4/sel4test-manifest#6]
Hello,

I'm currently trying to build sel4test for spike and Ariane following the steps described in [https://docs.sel4.systems/Hardware/RISCV.html](https://docs.sel4.systems/Hardware/RISCV.html).

However, the build process fails. The reference to `ltimer_default_init()` in [projects/sel4test/apps/sel4test-driver/main.c](https://github.com/seL4/sel4test/blob/master/apps/sel4test-driver/src/main.c) is undefined for both of the platforms above, thus causing an error when linking. In fact, this function seems to be defined for most platforms individually in [projects/util_libs/libplatsupport/src/plat/](https://github.com/seL4/util_libs/tree/master/libplatsupport/src/plat). But the subdirectories `spike/` and `ariane/` (amongst others) are missing a file `ltime.c` with a definition of `ltimer_default_init()`.

Am I missing something obvious here or is this something that needs to be fixed?

Best,
Nils

**Comment by kent-mcleod** [comment]
In this case it should be that you need to set SIMULATION=ON via `cmake -DSIMULATION=ON .` which disables timer and cache tests.  This will result in sel4test not trying to initialise a user level timer, which isn't supported for the ariane.

**Comment by niwis** [comment]
Cheers!
